version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2180
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2180:2180"

  kafka:
    image: confluentinc/cp-kafka:7.2.2
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2180
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER_ENV: "true"
    ports:
      - "5000:5000"
    depends_on: 77
      - redis
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  
